export enum allTagTypes {
  register = "register",
  lostItem = "lostItem",
  foundItem = "foundItem",
  userProfile = "userProfile",
  userUpdateProfile = "userUpdateProfile",
  userUpdatePassword = "userUpdatePassword",
  getLostItem = "getLostItem",
  foundLostItem = "foundLostItem",
  createClaim = "createClaim",
  getClaimItem = "getClaimItem",
  getSingleProductClaim = "getSingleProductClaim",
  updateClaimStatus = "updateClaimStatus",
  getAllUser = "getAllUser",
  updateStatus = "updateStatus",
  getAllLostItem = "getAllLostItem",
  updateLostItemStatus = "updateLostItemStatus",
  getAllStatistics = "getAllStatistics",
}

export const allTagList = [
  allTagTypes.register,
  allTagTypes.lostItem,
  allTagTypes.foundItem,
  allTagTypes.userProfile,
  allTagTypes.userUpdateProfile,
  allTagTypes.userUpdatePassword,
  allTagTypes.getLostItem,
  allTagTypes.foundLostItem,
  allTagTypes.createClaim,
  allTagTypes.getClaimItem,
  allTagTypes.getSingleProductClaim,
  allTagTypes.updateClaimStatus,
  allTagTypes.getAllUser,
  allTagTypes.updateStatus,
  allTagTypes.getAllLostItem,
  allTagTypes.updateLostItemStatus,
  allTagTypes.getAllStatistics,
];
